<%@ Page Language="VB" MasterPageFile="~/MasterPage1.master" AutoEventWireup="false" CodeFile="ChangePassword.aspx.vb" Inherits="Membership_ChangePassword" title="Untitled Page" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">
  <asp:UpdatePanel id="UpdatePanel1" runat="server">   
<contenttemplate>
<TABLE style="WIDTH: 820px"><TBODY><TR><TD style="WIDTH: 820px" class="TitleRow">CHANGE PASSWORD</TD></TR><TR><TD style="WIDTH: 820px"><asp:Panel id="Panel3" runat="server" Width="100%" BorderWidth="1px" BorderStyle="Solid" BorderColor="DeepSkyBlue" __designer:wfdid="w10"><TABLE style="WIDTH: 100%"><TBODY><TR><TD style="FONT-SIZE: 10pt; WIDTH: 25%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold">Old Password :</TD><TD style="WIDTH: 75%" class="text2"><asp:TextBox id="txtoldpassword" runat="server" Width="300px" __designer:dtid="562949953421328" __designer:wfdid="w12" TextMode="Password"></asp:TextBox><asp:RequiredFieldValidator id="RequiredFieldValidator1" runat="server" __designer:dtid="562949953421329" __designer:wfdid="w15" ControlToValidate="txtoldpassword" ErrorMessage="*" ValidationGroup="Change"></asp:RequiredFieldValidator></TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 25%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold">New Password :</TD><TD style="WIDTH: 75%" class="text2"><asp:TextBox id="txtnewpassword" runat="server" Width="300px" __designer:dtid="562949953421333" __designer:wfdid="w13" TextMode="Password"></asp:TextBox><asp:RequiredFieldValidator id="RequiredFieldValidator2" runat="server" __designer:dtid="562949953421334" __designer:wfdid="w16" ControlToValidate="txtnewpassword" ErrorMessage="*" ValidationGroup="Change"></asp:RequiredFieldValidator></TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 25%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold">Confirm New Password :</TD><TD style="WIDTH: 75%" class="text2"><asp:TextBox id="txtconfirmpassword" runat="server" Width="300px" __designer:dtid="562949953421338" __designer:wfdid="w14" TextMode="Password"></asp:TextBox><asp:RequiredFieldValidator id="RequiredFieldValidator3" runat="server" __designer:dtid="562949953421339" __designer:wfdid="w17" ControlToValidate="txtconfirmpassword" ErrorMessage="*" ValidationGroup="Change"></asp:RequiredFieldValidator></TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 25%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold"></TD><TD style="WIDTH: 75%" class="text2"><asp:Label id="lblerror" runat="server" ForeColor="Red" __designer:dtid="562949953421342" __designer:wfdid="w19"> </asp:Label></TD></TR><TR><TD class="text3" colSpan=2><asp:Button id="Button1" runat="server" CssClass="CSButton" Width="200px" Height="35px" Text="Change Password" __designer:dtid="562949953421346" __designer:wfdid="w20" ValidationGroup="Change"></asp:Button> <cc1:confirmbuttonextender id="ConfirmButtonExtender1" runat="server" __designer:dtid="562949953421351" __designer:wfdid="w21" confirmtext="Are you sure you want to change your password?" targetcontrolid="Button1">
                                </cc1:confirmbuttonextender></TD></TR><TR><TD class="text3" colSpan=2></TD></TR></TBODY></TABLE></asp:Panel><BR /></TD></TR><TR><TD style="WIDTH: 820px" class="TitleRow">FORGOT PASSWORD</TD></TR><TR><TD style="WIDTH: 820px"><asp:Panel id="Panel4" runat="server" Width="100%" BorderWidth="1px" BorderStyle="Solid" BorderColor="DeepSkyBlue" __designer:wfdid="w11"><TABLE style="WIDTH: 100%"><TBODY><TR><TD style="FONT-SIZE: 10pt; WIDTH: 25%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold">Username :</TD><TD style="WIDTH: 75%" class="text2"><asp:TextBox id="txtuser" runat="server" Width="200px" __designer:dtid="844424930132009" __designer:wfdid="w22" ValidationGroup="forgot"></asp:TextBox><asp:RequiredFieldValidator id="RequiredFieldValidator5" runat="server" __designer:dtid="844424930132010" __designer:wfdid="w23" ControlToValidate="txtuser" ErrorMessage="*" ValidationGroup="forgot"></asp:RequiredFieldValidator></TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 25%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold">When is your birthday? :&nbsp;</TD><TD style="WIDTH: 75%" class="text2"><asp:TextBox id="TextBox1" runat="server" Width="200px" __designer:dtid="844424930132014" __designer:wfdid="w24"></asp:TextBox><asp:RequiredFieldValidator id="RequiredFieldValidator4" runat="server" __designer:dtid="844424930132015" __designer:wfdid="w25" ControlToValidate="TextBox1" ErrorMessage="*" ValidationGroup="forgot"></asp:RequiredFieldValidator><asp:ImageButton id="ImageButton1" runat="server" ImageUrl="~/images/Calendar_scheduleHS.png" __designer:dtid="844424930132016" __designer:wfdid="w26"></asp:ImageButton></TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 25%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold"></TD><TD style="WIDTH: 75%" class="text2"><cc1:CalendarExtender id="CalendarExtender1" runat="server" __designer:dtid="844424930132020" __designer:wfdid="w30" TargetControlID="TextBox1" PopupButtonID="ImageButton1">
                    </cc1:CalendarExtender><cc1:MaskedEditExtender id="MaskedEditExtender1" runat="server" __designer:dtid="844424930132021" __designer:wfdid="w31" TargetControlID="TextBox1" MaskType="Date" Mask="99/99/9999">
                    </cc1:MaskedEditExtender></TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 25%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold">Password :</TD><TD style="WIDTH: 75%" class="text2"><asp:Label id="Label1" runat="server" __designer:dtid="844424930132025" __designer:wfdid="w27"></asp:Label></TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 25%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold"></TD><TD style="WIDTH: 75%" class="text2"><asp:Label id="lblinfo" runat="server" ForeColor="Red" __designer:dtid="844424930132029" __designer:wfdid="w33"></asp:Label></TD></TR><TR><TD class="text3" colSpan=2><asp:Button id="Button2" runat="server" CssClass="CSButton" Width="200px" Height="35px" Text="Retrieve Password" __designer:dtid="844424930132035" __designer:wfdid="w29" ValidationGroup="forgot"></asp:Button></TD></TR><TR><TD class="text3" colSpan=2></TD></TR></TBODY></TABLE></asp:Panel><BR /></TD></TR></TBODY></TABLE>
</contenttemplate>
</asp:UpdatePanel>  &nbsp; &nbsp;
</asp:Content>

