<%@ Page Language="VB" MasterPageFile="~/masterpage1.master" AutoEventWireup="false" CodeFile="CreatingUserAccounts.aspx.vb" Inherits="Membership_CreatingUserAccounts" title="Web Systems Manager" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">
<asp:UpdatePanel id="UpdatePanel1" runat="server">   
<contenttemplate>
<TABLE style="WIDTH: 820px"><TBODY><TR><TD style="WIDTH: 820px" class="TitleRow">CREATE A NEW USER ACCOUNT</TD></TR><TR><TD style="WIDTH: 820px"><asp:Label id="CreateAccountResults" runat="server" ForeColor="#CC0000" __designer:dtid="2251799813685253" __designer:wfdid="w40"></asp:Label></TD></TR><TR><TD style="WIDTH: 820px"><asp:Panel id="Panel1" runat="server" Width="100%" __designer:wfdid="w39" BorderStyle="Solid" BorderColor="DeepSkyBlue" BorderWidth="1px"><TABLE style="WIDTH: 100%"><TBODY><TR><TD style="FONT-SIZE: 10pt; WIDTH: 20%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold">Username : </TD><TD style="WIDTH: 80%" class="text2"><asp:TextBox id="Username" runat="server" Width="250px" Font-Size="10pt" Font-Names="Verdana" __designer:dtid="2251799813685259" __designer:wfdid="w41"></asp:TextBox>*</TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 20%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold">Password :</TD><TD style="WIDTH: 80%" class="text2"><asp:TextBox id="Password" runat="server" Width="250px" Font-Size="10pt" Font-Names="Verdana" __designer:dtid="2251799813685263" __designer:wfdid="w42" TextMode="Password"></asp:TextBox>*</TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 20%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold">Confirm Password :</TD><TD style="WIDTH: 80%" class="text2"><asp:TextBox id="ConfirmPassword" runat="server" Width="250px" Font-Size="10pt" Font-Names="Verdana" __designer:dtid="2251799813685267" __designer:wfdid="w43" TextMode="Password"></asp:TextBox>*</TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 20%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold">E-mail Address : </TD><TD style="WIDTH: 80%" class="text2"><asp:TextBox id="Email" runat="server" Width="250px" Font-Size="10pt" Font-Names="Verdana" __designer:dtid="2251799813685271" __designer:wfdid="w44"></asp:TextBox>*</TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 20%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold"><asp:Label id="SecurityQuestion" runat="server" __designer:dtid="2251799813685274" __designer:wfdid="w45"></asp:Label>:</TD><TD style="WIDTH: 80%" class="text2"><asp:TextBox id="SecurityAnswer" runat="server" Width="120px" Font-Size="10pt" Font-Names="Verdana" __designer:dtid="2251799813685276" __designer:wfdid="w46"></asp:TextBox><asp:ImageButton id="ImageButton1" runat="server" ImageUrl="~/images/Calendar_scheduleHS.png" __designer:dtid="2251799813685277" __designer:wfdid="w47"></asp:ImageButton>*</TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 20%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold"></TD><TD style="WIDTH: 80%" class="text2"><cc1:CalendarExtender id="CalendarExtender1" runat="server" __designer:dtid="2251799813685281" __designer:wfdid="w48" TargetControlID="SecurityAnswer" PopupButtonID="ImageButton1">
                    </cc1:CalendarExtender><cc1:MaskedEditExtender id="MaskedEditExtender1" runat="server" __designer:dtid="2251799813685282" __designer:wfdid="w49" TargetControlID="SecurityAnswer" MaskType="Date" Mask="99/99/9999">
                    </cc1:MaskedEditExtender> </TD></TR><TR><TD class="TitleRow" colSpan=2>PERSONAL INFORMATION</TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 20%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold">First Name : </TD><TD style="WIDTH: 80%" class="text2"><asp:TextBox id="txtFName" runat="server" Width="250px" Font-Size="10pt" Font-Names="Verdana" __designer:dtid="281474976710690" __designer:wfdid="w1"></asp:TextBox>*</TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 20%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold">Middle Initial :</TD><TD style="WIDTH: 80%" class="text2"><asp:TextBox id="txtMI" runat="server" Width="50px" Font-Size="10pt" Font-Names="Verdana" __designer:dtid="281474976710694" __designer:wfdid="w2"></asp:TextBox></TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 20%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold">Last Name : </TD><TD style="WIDTH: 80%" class="text2"><asp:TextBox id="txtLName" runat="server" Width="250px" Font-Size="10pt" Font-Names="Verdana" __designer:dtid="281474976710698" __designer:wfdid="w3"></asp:TextBox>*</TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 20%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold">Contact Number :</TD><TD style="WIDTH: 80%" class="text2"><asp:TextBox id="txtContact" runat="server" Width="150px" Font-Size="10pt" Font-Names="Verdana" __designer:dtid="281474976710702" __designer:wfdid="w4"></asp:TextBox></TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 20%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold">Department : </TD><TD style="WIDTH: 80%" class="text2"><asp:TextBox id="txtDept" runat="server" Width="250px" Font-Size="10pt" Font-Names="Verdana" __designer:dtid="281474976710706" __designer:wfdid="w5"></asp:TextBox></TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 20%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold">Position : </TD><TD style="WIDTH: 80%" class="text2"><asp:TextBox id="txtPosition" runat="server" Width="250px" Font-Size="10pt" Font-Names="Verdana" __designer:dtid="281474976710710" __designer:wfdid="w6"></asp:TextBox></TD></TR><TR><TD style="FONT-SIZE: 10pt; WIDTH: 20%; FONT-FAMILY: Verdana; TEXT-ALIGN: left" class="text1Bold"></TD><TD style="WIDTH: 80%" class="text2"></TD></TR><TR><TD class="text3" colSpan=2><asp:Button id="CreateAccountButton" runat="server" CssClass="CSButton"  Width="200px" Height="35px" Text="Create Account" __designer:dtid="281474976710714" __designer:wfdid="w8"></asp:Button></TD></TR><TR><TD class="text3" colSpan=2></TD></TR></TBODY></TABLE></asp:Panel></TD></TR><TR><TD style="WIDTH: 820px" class="text3"><asp:Label id="InvalidUserNameOrPasswordMessage" runat="server" ForeColor="Red" __designer:dtid="281474976710716" __designer:wfdid="w9" Visible="false" EnableViewState="false"></asp:Label></TD></TR><TR><TD style="WIDTH: 820px"></TD></TR></TBODY></TABLE>
</contenttemplate>
</asp:UpdatePanel>   
    
   
</asp:Content>