<%@ Page Language="VB" MasterPageFile="~/masterpage1.master" AutoEventWireup="false" CodeFile="UserInformation.aspx.vb" Inherits="Administration_UserInformation" title="Web Systems Manager" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">
<asp:UpdatePanel id="UpdatePanel1" runat="server">   
<contenttemplate>
<TABLE style="WIDTH: 820px"><TBODY><TR><TD style="WIDTH: 820px" class="TitleRow">USER INFORMATION</TD></TR><TR><TD style="WIDTH: 820px"></TD></TR><TR><TD style="WIDTH: 820px" class="text2"><asp:HyperLink id="BackLink" runat="server" NavigateUrl="ManageUsers.aspx" __designer:dtid="1970324836974597" __designer:wfdid="w21">&lt;&lt; Back to User List</asp:HyperLink></TD></TR><TR><TD style="WIDTH: 820px" class="text2"><asp:Panel id="Panel1" runat="server" Width="100%" __designer:wfdid="w32" BorderColor="DeepSkyBlue" BorderStyle="Solid" BorderWidth="1px"><TABLE style="WIDTH: 100%"><TBODY><TR><TD style="WIDTH: 20%" class="text1Bold"></TD><TD style="WIDTH: 80%"></TD></TR><TR><TD style="WIDTH: 20%" class="text1Bold">Username : </TD><TD style="WIDTH: 80%"><asp:Label id="UserNameLabel" runat="server" __designer:dtid="1970324836974602" __designer:wfdid="w33"></asp:Label></TD></TR><TR><TD style="WIDTH: 20%" class="text1Bold">Approved : </TD><TD style="WIDTH: 80%" class="text2"><asp:CheckBox id="IsApproved" runat="server" __designer:dtid="1970324836974606" AutoPostBack="true" __designer:wfdid="w34"></asp:CheckBox></TD></TR><TR><TD style="WIDTH: 20%" class="text1Bold">Locked Out : </TD><TD style="WIDTH: 80%"><asp:Label id="LastLockoutDateLabel" runat="server" __designer:dtid="1970324836974610" __designer:wfdid="w35"></asp:Label></TD></TR><TR><TD style="WIDTH: 20%" class="text1Bold">Role : </TD><TD style="WIDTH: 80%"><asp:Label id="lblRole" runat="server" Text="" __designer:dtid="1970324836974616" __designer:wfdid="w36"></asp:Label></TD></TR><TR><TD style="WIDTH: 20%" class="text1Bold"></TD><TD style="WIDTH: 80%"><asp:Button id="UnlockUserButton" runat="server" Width="150px" Text="Unlock User" __designer:dtid="1970324836974612" __designer:wfdid="w37"></asp:Button></TD></TR><TR><TD class="text3" colSpan=2></TD></TR><TR><TD class="text3" colSpan=2><asp:Label id="StatusMessage" runat="server" __designer:dtid="1970324836974618" CssClass="Important" __designer:wfdid="w38"></asp:Label></TD></TR></TBODY></TABLE></asp:Panel></TD></TR><TR><TD style="WIDTH: 820px" class="TitleRow">DEFINE USER ROLE</TD></TR><TR><TD style="WIDTH: 820px" class="text2"><TABLE style="WIDTH: 100%"><TBODY><TR><TD style="WIDTH: 20%" class="text1Bold">Select a Role :</TD><TD style="WIDTH: 80%" class="text2"><asp:DropDownList id="RoleList" runat="server" Width="250px" __designer:dtid="1970324836974623" AutoPostBack="true" __designer:wfdid="w30"></asp:DropDownList><asp:Button id="AddUserToRoleButton" runat="server" Width="150px" Text="Add User to Role" __designer:dtid="1970324836974624" __designer:wfdid="w31"></asp:Button></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
</contenttemplate>
</asp:UpdatePanel>
</asp:Content>
